### ISSUE TITLE
Can we check the effect of each module in probit poisson log normal model in Table 5?

### ISSUE THREAD

**Issue by kuang-da** [kuang-da/health-care-reform-analysis#2]
It would be great if we could reproduce and reach the conclusion that the left tail of the distribution was affected more by the reform.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/18092300/148637099-84ac0a61-1851-477d-bb75-df3542e36afd.png">

**Comment by UroborousDaFalconia** [comment]
Need to show the effect of disproportionate effects on less frequent users and more frequent users

**Comment by kuang-da** [comment]
Associated with #1

**Comment by kuang-da** [comment]
Mark as resolved.
